name: Deploy

on:
  push:
    branches:
 #     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push Docker image
      uses: aws-actions/amazon-ecr-build-and-push-action@v1
      with:
        # The AWS credentials to use for pushing the image
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # The ECR registry to push the image to
        registry: ${{ secrets.ECR_REGISTRY }}
        # The path to the Dockerfile and context
        build-context: .
        # The tag to apply to the image
        tag: latest
    - name: Deploy with Terraform
      run: terraform init && terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
