name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker image
      uses: aws-actions/amazon-ecr-build-and-push-action@v1
      with:
        # The AWS credentials to use for pushing the image
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        # The ECR registry to push the image to
        registry: ${{ env.ECR_REGISTRY }}
