name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set Relase version
      id: vars
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Login to Amazon ECR
       env:
        # The AWS credentials to use for pushing the image
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: build docker image and push to ecr repo
      run: |
        docker build -t ${{ env.ECR_REPOSITORY}}/nodeapp:${{ env.RELEASE_VERSION}} .
        docker push ${{ env.ECR_REPOSITORY}}/nodeapp:${{ env.RELEASE_VERSION}}
        
