name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build Docker image
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        # The AWS credentials to use for pushing the image
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        # Build a docker container and push it to ECR so that it can be deployed to ECS.
        docker build .
        docker push ${{ env.ECR_REGISTRY}}/{{ env.$ECR_REPOSITORY}}/my_image
        echo "image=${{ env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY}}" >> $GITHUB_OUTPUT
